# -*- coding: utf-8 -*-
"""testnb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/embedded/projects/handy-bindery-451813-e1/locations/us-central1/repositories/78a2c89d-504d-454b-8a2b-4e1d0698a4c7
"""

#My app for analysis
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/ajaykuma/Datasets_For_Work/refs/heads/main/Bank_full.csv")

#df

df.head()

df.describe()

df[df.age > 80].count()

